# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/rosa/bin/Py/Gui/list.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os, sys
# form qt5 designe
import gui.py

# classe form per collegare gui qt5
class Xxx(QtWidgets.QMainWindow, Ui_xxx):
    # Set initial path to current working directory
    savedir = os.getcwd()

# inizializzazioni
    def __init__(self, parent=None):
        super(xxx, self).__init__(parent)
        self.setupUi(self)
# collegate funz ai boyttoni
        self.OpenButton.clicked.connect(self.proc)

#- proc
    def proc(self):

# collegare root
        root = tkinter.Tk()
        root.withdraw()
#

def Messaggio(msgT, msgE):
    msg = QtWidgets.QMessageBox()
    msg.setIcon(QtWidgets.QMessageBox.Warning)
    msg.setText(msgT)
    msg.setInformativeText(msgE)
    msg.setWindowTitle("Errore")
    msg.setStandardButtons(QtWidgets.QMessageBox.Ok)
    msg.exec_()

##-- inizio
def main():
    app = QtWidgets.QApplication(sys.argv)
    form = Xxx()
    form.show()
    app.exec_()

if __name__ == '__main__':
    main()
