#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/rosa/bin/Py/Gui/list.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os, sys, csv, time
#import pyperclip as clip
import tkinter, tkinter.filedialog
#import signal
import gi
gi.require_version('Gdk', '4.0')
gi.require_version('Gtk', '4.0')
from gi.repository import Gtk as gtk, Gdk, GLib

from pyConfigParser import ConfigIni
from hashlib import blake2s
from base64 import b64encode #b64decode,

import gpo_dlgV2
from PyQt5 import QtWidgets
from PyQt5.QtWidgets import QApplication, QMessageBox, QSystemTrayIcon, QMenu, QAction
from PyQt5.QtGui import QIcon
from PyQt5.QtCore import QEventLoop
#from isrun import isrun

configDir = os.getenv('HOME')+ "/.config/gpo"
nomeDiz = 'Gpo.diz'
nomeIni = 'Gpo.ini'
siGPO = False
formGPO = None
gtk.Settings.get_default().set_property("gtk-icon-theme-name", "Numix")

def Messaggio(msgT, msgE, icona=QMessageBox.Critical):
    msgBox = QMessageBox()
    msgBox.setWindowTitle(msgT)
    msgBox.setText(msgE)
    msgBox.setIcon(icona)
    msgBox.setStandardButtons(QMessageBox.Ok)  #| QMessageBox.Cancel
    msgBox.buttonClicked.connect(msgButtonClick)

    returnValue = msgBox.exec()
    '''if returnValue == QMessageBox.Ok:
        print('OK clicked')'''

def msgButtonClick(i):
    pass
    #print("Button clicked is:",i.text())

def copyClipTK(testo):
    r = tkinter.Tk()
    r.withdraw()
    r.clipboard_clear()
    time.sleep(1)
    r.clipboard_append(testo)
    r.update()
    #r.destroy()

    time.sleep(1)

def osCopyClip(testo):
    ss = 'echo "' +testo+ '" | xclip'
    x = os.system(ss)

def clipBoard(testo):
    cb = gtk.Clipboard.get(Gdk.SELECTION_CLIPBOARD)

    #cb.set_text("", 0)
    cb.set_text('', -1)
    cb.set_text(testo, -1)
    clip = cb.wait_for_text()
    if clip is None:
        return 'ERRORE'
    else:
        return clip

def geClipBoard(testo):

    clipboard = Gdk.Display.get_default().get_clipboard()
    time.sleep(1)

    clipboard.set(testo)
    time.sleep(1)
    clipboard.read_text_async(None, on_paste_text)

def on_paste_text(clipboard, result):
    text = clipboard.read_text_finish(result)
    '''if text is None:
        Messaggio(  'Creazione password', 'Pwd: creata ma non copiata negli appunti')
    else:
        Messaggio(  'Creazione password', 'Pwd: '+ text +
                    ' \ncopiata negli appunti') '''

    print ('clip paste ',text)
    #main_loop.quit()

#- ttutto ciò che viene dichiarato in class..() diventa proptietà di self.
def Importa(fileImport, selfDiz, creaIni = True):
    arrayCmbUrl = []
    '''
    arrayCmbUrl.append([])
    arrayCmbUrl[0].append(' ')
    arrayCmbUrl[0].append(' ')
    arrayCmbUrl[0].append(' ')
    configDir = os.getenv('HOME')+ "/.config/gpo"
    '''
    idx = 0

# Define the custom dialect
    diz = csv.register_dialect("diz", delimiter=",", quotechar='"', quoting=csv.QUOTE_MINIMAL)

# Open the file in read mode
    if creaIni:
        configuraPWD = ConfigIni(configDir, 'Gpo.ini')
    else:
        fdiz = open(selfDiz, "w")

    with open(fileImport, "r") as csv_file:
        # Create a reader object, using the custom dialect
        csv_reader = csv.reader(csv_file, dialect="diz")
        # Read the data from the file
        for row in csv_reader:
            # Process the data in the row
            #print(row[0])

            if row[0].find('http') == 0:
                arrayCmbUrl.append([])

                arrayCmbUrl[idx].append(row[0])
                arrayCmbUrl[idx].append(row[1])
                arrayCmbUrl[idx].append(row[2])

                if creaIni:
                    configuraPWD.sezione(row[0])
                    configuraPWD.sezione(row[0],"Utente",row[1])
                    configuraPWD.sezione(row[0],"Passwowd",row[2])
                else:
                    fdiz.writelines('"'+row[0]+'","'+row[1]+'","'+row[2] +'"\n')

                idx += 1
        if creaIni:
            configuraPWD.salva()
        else:
            fdiz.close()

    arrayCmbUrl.sort()
    return arrayCmbUrl

class Gpo(QtWidgets.QMainWindow, gpo_dlgV2.Ui_GPO):
    loop= None
    siGPO = True

    #def __get__():
    #- serve solo per capire se sto/devo mostrato la form
    def Sigpo():
        return Gpo.siGPO

    def caricaDati(self):
        self.totItems = 0
        self.curIdxCmb = 0
        self.arrayCmbUrl = []

    # Set initial path to current working directory
        selfDiz = configDir + "/" + nomeDiz
        if len(sys.argv) == 2:
            fileImport = sys.argv[1]
            if os.path.exists(fileImport):
                self.arrayCmbUrl = Importa(fileImport, selfDiz)
            else:
                #raise 'file importazione inesistente'
                pass
        else:
        #- carica tutto
            if os.path.exists(selfDiz):
                self.arrayCmbUrl = []
                self.configuraGpo = ConfigIni(configDir, nomeDiz)

                self.arrayCmbUrl = self.configuraGpo.leggiIni(3) #- 3 elem vuoti
                self.arrayCmbUrl.sort

            else:
                #raise 'file importazione inesistente'
                os.makedirs(configDir)
                File = open(selfDiz, 'w')
                File.close()

#-- init dialog
    def __init__(self, parent=None):
        super(Gpo, self).__init__(parent)

        self.setupUi(self)
        self.setGeometry(400, 150, 627, 246)

        self.cmbUrl.setEnabled(False)
        self.btnCrea.clicked.connect(self.Crea)
        self.btnChiudi.clicked.connect(self.Chiudi)
        self.btnCopy.clicked.connect(self.Copy)
        self.btnSal.clicked.connect(self.Sal)
        self.btnPulisci.clicked.connect(self.Pulisci)
        #self.cmbUrl.changeEvent.connect()  #- self.text_changed
        self.cmbUrl.currentTextChanged.connect(self.Selcmb)

        '''
        self.cmbUrl.activated.connect(self.check_index)
        self.cmbUrl.activated.connect(self.current_text)
        self.cmbUrl.activated.connect(self.current_text_via_index)
        self.cmbUrl.activated.connect(self.current_count)

        def check_index(self, index):
            cindex = self.combobox.currentIndex()
            print(f"Index signal: {index}, currentIndex {cindex}")

        def current_text(self, _): # We receive the index, but don't use it.
            ctext = self.combobox.currentText()
            print("Current text", ctext)

        def current_text_via_index(self, index):
            ctext = self.combobox.itemText(index)  # Get the text at index.
            print("Current itemText", ctext)

        def current_count(self, index):
            count = self.combobox.count()
            print(f"Index {index+1}/{count}")
        '''

        #self.cmbUrl.addItems(self.arrayCmbUrl)
        idx = 0
        self.loop = None
        self.passwd = ""
        self.salvare = False
        self.caricaDati()
        for row in self.arrayCmbUrl:
            self.cmbUrl.addItem(row[0], idx)
            idx += 1

        self.totItems = idx
        self.lbUti.setEnabled(True)
        self.cmbUrl.setEnabled(True)
        self.cmbUrl.setCurrentIndex = 1
        self.btnSal.setEnabled(False)
        Gpo.siGPO = False
        self.show()
#-- init dialog

    def Crea(self):
        cmbidx: int # = ''
        url = self.lblUrl.text()        
        # self.cmbUrl.setItemText(cmbidx, url)
        # self.cmbUrl.setCurrentIndex(index=cmbidx)
        cmbidx = self.cmbUrl.findText(url)
        self.curIdxCmb = cmbidx
        self.cmbUrl.setCurrentText(url)
        if cmbidx:
            self.lblUrl.setText("")
            Messaggio("Messaggio Errore", "Password gia esistente")
            
        else:
            uti = self.lbUti.text().strip()
            if uti == "":
                Messaggio("Messaggio Errore", "Utente mancante")
                return 0

            daSx = url.find("www.")
            if daSx == -1:
                daSx = url.find("://") -1

            daSx += 4
            daDx = url.rfind(".")
            if daDx == -1:
                Messaggio("Messaggio Errore", "Controllare URL inserito")
                return 0

            primo = url[daSx:daDx]
            primo = primo[0:1].upper()
            pwd = ("123"+primo+url[daSx+1:daDx]+"!")

            idx = self.totItems
            if idx == 0:
                self.arrayCmbUrl.append([])
                self.arrayCmbUrl[idx].append(" ")
                self.arrayCmbUrl[idx].append(" ")
                self.arrayCmbUrl[idx].append(" ")
                self.cmbUrl.addItem(' ', idx)
                idx +=1

            #uti = self.lbUti.text()

            self.arrayCmbUrl.append([])
            self.arrayCmbUrl[idx].append(url)
            self.arrayCmbUrl[idx].append(uti)
            self.arrayCmbUrl[idx].append(pwd)
            self.arrayCmbUrl.sort()
            self.totItems = idx
            
            self.cmbUrl.addItem(url, idx)
            self.cmbUrl.setCurrentText(' ')

            self.configuraGpo.sezione(url,'utente', uti)
            self.configuraGpo.sezione(url,'password', pwd)
      
            self.lblPwd.setText(pwd)
            self.lblPwdSav.setText(pwd)
            self.lbUti.setReadOnly(False)
            self.btnSal.setEnabled(True)

        #self.cmbUrl.setCurrentIndex('0')
        #self.btnSal.setEnabled(True)
        #self.lblPwd.setText("")
        #url = self.lblUrl.setText("")
        #uti = self.lbUti.setText("")
        #pwd = self.lblPwdSav.setText("")

    def Sal(self):
        uti = self.lbUti.text().strip()
        if uti == "":
            Messaggio("Messaggio Errore", "Utente mancante")
            return 0

        url = self.cmbUrl.currentText()
        uti = self.lbUti.text()
        pwd = self.lblPwdSav.text()
        self.arrayCmbUrl[self.curIdxCmb][2] = pwd
        self.configuraGpo.sezione(url,'utente', uti)
        self.configuraGpo.sezione(url,'password', pwd)
        self.configuraGpo.salva()

        '''
        fileImport = self.selfDiz
        with open(fileImport, "a") as file:
            file.writelines('"'+url+'","'+uti+'","'+pwd+'"\n')
            file.close
        '''

        self.cmbUrl.setCurrentText(' ')
        self.lblPwd.setText("")
        self.lblUrl.setText("")
        self.lbUti.setText("")
        self.lblPwdSav.setText("")
        self.btnSal.setEnabled(False)
        self.salvare = False

    def Copy(self):
        if self.lblPwd.text().strip() == "":
            Messaggio("Messaggio Errore", "Password mancante")
            return 0

        iniFile = configDir + "/" + nomeIni
        with open(iniFile, "r") as file:
            key = file.readline()
            file.close

        pwd = self.lblPwdSav.text(); idx = pwd.find('#'); nCar = 0; I = ''
        if idx >-1:
            da = idx +1
            if pwd[len(pwd)-1:] == 'I':    #.find('F'):
                I = 'I'

            nCar = int(pwd[da:da+2])
            pwd = pwd[:idx]

        #key = b'23711'
        key = key.encode()
        h = blake2s(key=key)
        h.update(pwd.encode())
        dig = h.digest()
        pe=b64encode(dig).decode('utf-8')
        if nCar:
            if I == 'I':
                pe = pe[:nCar]
            else:
                pe = pe[-nCar:]

        '''
        h = hashlib.sha512()
        h.update(pwd.encode())
        pe = h.hexdigest()


        main_loop = GLib.MainLoop.new(None, True)
        main_loop.run()
        geClipBoard(pe)
        '''
        copyClipTK(pe)
        Messaggio('Password da copiare', pe, QMessageBox.Information)
        self.passwd = pe
        #clip.copy(pe) #+"X!"
        #self.lblPwdSav.setReadOnly(True)

        url = self.cmbUrl.currentText().strip()
        uti = self.lbUti.text()
        pwd = self.lblPwdSav.text()
        if url == '':
            url = self.lblPwd.text()

        pwdIni = self.configuraGpo.prendi(url, 'password')
        if pwdIni != pwd or pwdIni.strip() == '':
            self.btnSal.setEnabled(True)
            self.salvare = True

    def Pulisci(self):
        self.cmbUrl.setCurrentText(' ')
        self.lblPwd.setText("")
        self.lblUrl.setText("")
        self.lbUti.setText("")
        self.lblPwdSav.setText("")
        self.btnSal.setEnabled(False)
        self.salvare = False

        '''
        self.curIdxCmb = self.cmbUrl.currentIndex()

        self.lblUrl.setText(self.arrayCmbUrl[self.curIdxCmb][0])
        self.lblPwdSav.setText(self.arrayCmbUrl[self.curIdxCmb][2])
        self.lbUti.setText(self.arrayCmbUrl[self.curIdxCmb][1])
        self.lblPwdSav.setReadOnly(False)
        #self.lbUti.setReadOnly(False)
        self.btnSal.setEnabled(True)
        '''

    def Selcmb(self):
        if self.cmbUrl.currentIndex():
            self.curIdxCmb = self.cmbUrl.currentIndex()
        
        self.lbUti.setText(self.arrayCmbUrl[self.curIdxCmb][1])
        self.lblPwdSav.setText(self.arrayCmbUrl[self.curIdxCmb][2])

        #-print(self.arrayCmbUrl[ikdxCmb][0]+'-'+self.arrayCmbUrl[ikdxCmb][1]+'-'+self.arrayCmbUrl[ikdxCmb][2])

    def Chiudi(self):
        if self.salvare:
            self.Sal()

        Gpo.siGPO = True
        self.salvare = False
        self.loop.quit
        self.close()

def fileDlg(ext, opt = False):
    reso = ''
    ext = "*." + ext
    if opt:
        reso = tkinter.filedialog.asksaveasfilename(initialdir=os.getenv('HOME'),
                                                    title="Salva con nome",
                                                    defaultextension=".csv",
                                                    filetypes=[("Files csv", "*.csv"),
                                                    ("Tutti i tipi", "*.*")])

        return reso
    else:
        reso = tkinter.filedialog.askopenfilename(  initialdir=os.getenv('HOME'),
                                                    title="Scegli il File in formato csv",
                                                    filetypes=(("Files csv", ext),
                                                    ("Tutti i tipi", "*.*")))

        return reso
    '''
    try:

    Exception:

    percorso = reso[0].name
    percorso = percorso[:reso[0].name.rfind('/')]
    nome = reso[0].name[reso[0].name.rfind('/')+1:]
    gNomeIni = gNome[:gNomeIni.index('.')]
    file = percorso +'/'+ nome
    '''

def impo():
    fileImport = fileDlg('csv', True)
    if len(fileImport):
        configDir = os.getenv('HOME')+ "/.config/gpo"
        selfDiz = configDir + '/Gpo.ini'
        arrayCmbUrl = Importa(fileImport, selfDiz)

def espo():
    fileEsport = fileDlg('*', True)
    if len(fileEsport):
        arrayCmbUrl = []
        configDir = os.getenv('HOME')+ "/.config/gpo"
        configuraGpo = ConfigIni(configDir, 'Gpo.ini')
        arrayCmbUrl = configuraGpo.leggiIni() #- 3 elem vuoti
        fdiz = open(fileEsport, "w")
        for row in arrayCmbUrl:
            fdiz.writelines('"'+row[0]+'","'+row[1]+'","'+row[2] +'"\n')

        fdiz.close()

def mostra():
    ExeGPO('param')

##-- inizio
def ExeGPO(): #main():
    global formGPO
    #app = QtWidgets.QApplication([])
    try:
        siGPO = Gpo.Sigpo()
    except:
        siGPO = False
        #Gpo.Chiudi()

    if siGPO:
        formGPO = Gpo()
        formGPO.loop = QEventLoop()

        siGPO = formGPO.siGPO

        formGPO.loop.exec()

        #screen_shot.widget_closed.connect(loop.quit)

        #sys.exit(app.exec_())

#menu = None
def sysTray_click(click):
    #global menu

    if click == 3:
        ExeGPO()

    elif click == 1:
        tray.setContextMenu(menu)

if __name__ == '__main__':
    app = QApplication([])
    app.setQuitOnLastWindowClosed(False)

    icon = QIcon.fromTheme("/usr/share/icons/AdwaitaLegacy/32x32/legacy/dialog-password.png")

    tray = QSystemTrayIcon()
    tray.activated.connect(sysTray_click)
    tray.setIcon(icon)
    tray.setVisible(True)

    #QAction(QIcon("/usr/share/icons/AdwaitaLegacy/32x32/legacy/dialog-password.png"), "Edit", menu)
    menu = QMenu()

    action1 = QAction(QIcon("csvUp.png"), "Importa csv", menu)
    action1.triggered.connect(impo)
    menu.addAction(action1)

    action2 = QAction(QIcon("csvDn.png"), "Esporta csv", menu)
    action2.triggered.connect(espo)
    menu.addAction(action2)

    action3 = QAction(QIcon("esci.png"), "Esci", menu)
    action3.triggered.connect(app.quit)
    menu.addAction(action3)

    #tray.setContextMenu(menu)

    app.exec_()
