# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/rosa/bin/Py/Gui/list.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(564, 403)
        self.lstCategarie = QtWidgets.QListWidget(Dialog)
        self.lstCategarie.setGeometry(QtCore.QRect(90, 10, 256, 192))
        self.lstCategarie.setAlternatingRowColors(True)
        self.lstCategarie.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.lstCategarie.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.lstCategarie.setSelectionRectVisible(True)
        self.lstCategarie.setObjectName("lstCategarie")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 71, 16))
        self.label.setObjectName("label")
        self.ClearButton = QtWidgets.QPushButton(Dialog)
        self.ClearButton.setGeometry(QtCore.QRect(450, 350, 80, 26))
        self.ClearButton.setObjectName("ClearButton")
        self.OpenButton = QtWidgets.QPushButton(Dialog)
        self.OpenButton.setGeometry(QtCore.QRect(270, 350, 80, 26))
        self.OpenButton.setObjectName("OpenButton")
        self.SaveButton = QtWidgets.QPushButton(Dialog)
        self.SaveButton.setGeometry(QtCore.QRect(360, 350, 80, 26))
        self.SaveButton.setObjectName("SaveButton")
        self.ClearButton.raise_()
        self.lstCategarie.raise_()
        self.label.raise_()
        self.OpenButton.raise_()
        self.SaveButton.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lstCategarie.setSortingEnabled(True)
        self.label.setText(_translate("Dialog", "&Categorie"))
        self.ClearButton.setText(_translate("Dialog", "Clear"))
        self.OpenButton.setText(_translate("Dialog", "Open"))
        self.SaveButton.setText(_translate("Dialog", "Save"))
